#!/usr/bin/env python3

import os, xml.etree.ElementTree as ET

diretoria_dados = "MapaRuas-materialBase/"

files = os.listdir(diretoria_dados + "texto")

files.sort()


def parse_xml(file_path):
    tree = ET.parse(file_path)
    root = tree.getroot()

    return root

def get_text(element):
    text = element.text or ''
    for sub_element in element:
        text += get_text(sub_element)
        text += sub_element.tail or ''
    return text


						# <figure>
						# 	<img src="../MapaRuas-materialBase/imagem/MRB-01-RuaDoCampo-nascente.PNG"">
						# 	<figcaption>Rua do Campo - vista nascente.</figcaption>
						# </figure> 

def generateImagens(figuras):
	res = ""
	for figura in figuras:
		res += f"""
						<figure>
							<img src="{figura[0]}">
							<figcaption>{figura[1]}</figcaption>
						</figure>
		"""
            
	return res

						# <p>
						# 	A <lugar>rua do Campo</lugar> é um troço da actual <lugar>rua D. Frei Caetano Brandao</lugar>, entre a <lugar>rua D. Diogo de Sousa</lugar> e o <lugar>largo Conselheiro Torres e Almeida</lugar>, 
						# 	tendo recebido esta designação na sessão da Câmara de <data>28.07.1890</data>.
						# </p>
def generatePara(paragrafos):
	res = ""
	for para in paragrafos:
		res += f"""
						<p>
							{get_text(para)}
						</p>
		"""
	return res

						# <li>
						# 	<casa>
						# 		<número>3</número>
						# 		<enfiteuta>Os herdeiros do Padre Domingos Tinoco</enfiteuta>
						# 		<foro>150 reis e 2 galinhas</foro>
						# 		<desc>
						# 			<p>
						# 				Confronta, de Sul, com parte da mesma casa foreira à <entidade tipo="instituição">Confraria da Trindade</entidade>, antiga <entidade tipo="instituição">Confraria da Companhia de Jesus</entidade> e, de Norte, com casa dízima a Deus
						# 			</p>
						# 		</desc>
						# 	</casa>
						# </li>
def generateCasas(casas):
	res = ""
	for casa in casas:
		res += f"""
						<li>
							<p>Número: {casa["número"]}</p>
							<p>enfiteuta: {casa["enfiteuta"]}</p>
							<p>foro: {casa["foro"]}</p>
		"""

		for para in casa["desc"]:
			res += f"""
							<p>{para}</p>	
			"""
		
		res += """
						</li>
		"""

	return res


for file in files:
	file_path = os.path.join(diretoria_dados + "texto", file)
	with open(file_path, 'r') as f:

		tree = parse_xml(file_path)

		nome = tree.find(".//nome").text.strip() # alguns tinham espacos a esquerda
		numero = tree.find(".//número").text.strip()

		print(f"a processar {numero}")

		figuras = []
		for fig in tree.findall(".//corpo//figura"):
			figuras.append((fig.find(".//imagem").attrib.get("path"), fig.find(".//legenda").text))
		
		# print(figuras)
		paragrafos = tree.findall(".//corpo/para")
		# for para in paragrafos:
		# 	print(get_text(para))

		casas = []
		for casa in tree.findall(".//lista-casas/casa"):
			numero_casa = casa.find(".//número")
			enfiteuta = casa.find(".//enfiteuta")
			foro = casa.find(".//foro")

			casadict = {
				"número" : numero_casa.text if numero_casa is not None else "N/A",
				"enfiteuta" : enfiteuta.text if enfiteuta is not None else "N/A",
				"foro" : foro.text if foro is not None else "N/A",
				"desc" : []
			}

			for para in casa.findall(".//desc/para"):
				casadict["desc"].append(get_text(para))
			casas.append(casadict)


		f.close()

		preHTML = f"""
		<!DOCTYPE html>
		<html lang="en">
			<head>
				<title>Lista de ruas de Braga: {nome}</title>
				<meta charset="UTF-8">
				<meta name="viewport" content="width=device-width, initial-scale=1">
				<link rel="stylesheet" href="w3.css">
			</head>

			<body>

				<div class="w3-card-4">

					<header class="w3-container w3-purple">
						<h3>Lista de ruas de Braga: {nome}</h3>
					</header>
					<div class="w3-container">
		"""

		imagensHTML = generateImagens(figuras)

		paraHTML = generatePara(paragrafos)

		casaspreHTML = f"""
					</div>
					<ul class="w3-ul w3-card-4" style="width:50%">
		"""

		casasHTML = generateCasas(casas)

		postHTML = """
					</ul>

					<footer class="w3-container w3-purple">
						<h5>Generated by MRBApp::EngWeb2024::A100538</h5>
					</footer>
				</div>
			</body>
		</html>
		"""
            


		pagHTML = preHTML + imagensHTML + paraHTML + casaspreHTML + casasHTML + postHTML

		outFile = open(f"./pages/mrb{numero}.html", "w")
		outFile.write(pagHTML)
		outFile.close()
