#!/usr/bin/env python3

import os, xml.etree.ElementTree as ET

diretoria_dados = "MapaRuas-materialBase/texto"

files = os.listdir(diretoria_dados)

files.sort()


def parse_xml(file_path):
    tree = ET.parse(file_path)
    root = tree.getroot()

    return root

preHTML = """
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Lista de ruas de Braga</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="w3.css">
	</head>

	<body>

		<div class="w3-card-4">

			<header class="w3-container w3-purple">
				<h3>Lista de ruas de Braga</h3>
			</header>

			<div class="w3-container">
				<ul class="w3-ul w3-card-4" style="width:50%">
"""	

posHTML = """
				</ul>
			</div>

			<footer class="w3-container w3-purple">
				<h5>Generated by MRBApp::EngWeb2024::A100538</h5>
			</footer>
		</div>
	</body>
</html>
"""



conteudoHTML = ""

for file in files:
	file_path = os.path.join(diretoria_dados, file)
	with open(file_path, 'r') as f:

		tree = parse_xml(file_path)

		nome = tree.find(".//nome").text.strip() # alguns tinham espacos a esquerda
		numero = tree.find(".//número").text.strip()

		f.close()

		conteudoHTML += f"""
					<li>
						<a href="mrb{numero}.html">{numero}: {nome}</a>
					</li>
		"""

pagHTML = preHTML + conteudoHTML + posHTML

outFile = open("./pages/index.html", "w")
outFile.write(pagHTML)
outFile.close()
