#!/usr/bin/env python3

import json

file = open("mapa-virtual.json", "r")
data = json.load(file)
file.close()

# [] ou {}??????
cidades = data.get("cidades", [])
ligacoes = data.get("ligacoes", [])

id_cidade = {}
for cidade in cidades:
	id_cidade[cidade["id"]] = cidade["nome"]

link_base = "/"
def geraLigacoes(ligacoes, id_origem):
	ligacoesHTML = ""
	for ligacao in ligacoes:
		if ligacao["origem"] == id_origem:
			id_destino = ligacao["destino"]
			# <a href="{link_base}{id_origem}">De: {id_cidade[id_origem]}</a>
			ligacoesHTML += f"""
			<a href="{link_base}{id_destino}">Para: {id_cidade[id_destino]}</a>
			<p>Distância: {ligacao["distância"]}</p>
			"""
		elif ligacao["destino"] == id_origem:
			ligacoesHTML += f"""
			<a href="{link_base}{ligacao["origem"]}">Para: {id_cidade[ligacao["origem"]]}</a>
			<p>Distância: {ligacao["distância"]}</p>
			"""
	return ligacoesHTML

for cidade in cidades:
	nome = cidade["nome"]
	preHTML = f"""
	<!DOCTYPE html>
	<html lang="en">
		<head>
			<title>Mapa virtual: {nome}</title>
			<meta charset="UTF-8">
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<link rel="stylesheet" href="w3.css">
		</head>

		<body>

			<header class="w3-container w3-purple">
				<h3>Mapa virtual: {nome}</h3>
			</header>
	"""

	cidadeHTML = f"""
			<p>Nome: {nome}</p>
			<p>População: {cidade["população"]}</p>
			<p>Descrição: {cidade["descrição"]}</p>
			<p>Distrito: {cidade["distrito"]}</p>
	"""

	ligacoesHTML = geraLigacoes(ligacoes, cidade["id"])

	posHTML = """
				<footer class="w3-container w3-purple">
					<h5>Generated by MapaVirtual::EngWeb2024::A100538</h5>
				</footer>
			</div>
		</body>
	</html>
	"""

	with open("./pages/" + cidade["id"] + ".html", "w") as outfile:
		outfile.write(preHTML + cidadeHTML + ligacoesHTML + posHTML)
